apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: cchapman
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ip-192-168-47-255.us-east-2.compute.internal
      containers:
      - envFrom:
        - configMapRef:
            name: feature-toggle
        - secretRef:
            name: db-secret
        name: app-deployment
        image: registry.dev.afsmtddso.com/cchapman-harbor-project/db:971c881-755a26b
        ports:
        - containerPort: 5000
